package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func cmdIndex(cfg Config, args []string) error {
	out, _ := flagValue(args, "--out")
	if out == "" {
		out = cfg.Index
	}
	if out == "" || out == "-" {
		return errors.New("index is disabled in jig.yml (index: -), pass --out PATH")
	}

	s, err := newScreen("index")
	if err != nil {
		return err
	}
	defer s.Close()

	var result scanResult
	err = s.Step("writing "+relTo(cfg.Root, out), func(report func(string)) error {
		result = scan(cfg)
		report(fmt.Sprintf("%d tools", len(result.Tools)))
		return os.WriteFile(out, []byte(renderIndex(cfg, result.Tools)), 0o644)
	})
	printManifestErrors(result.Errors)
	if err != nil {
		return err
	}

	fmt.Printf("%s · %d tools\n", out, len(result.Tools))
	return nil
}

func renderIndex(cfg Config, tools []Tool) string {
	var out strings.Builder

	fmt.Fprintf(&out, "# TOOLS.md — tools of %s\n\n", filepath.Base(cfg.Root))
	out.WriteString("Generated by `jig index`, do not edit by hand — edit the manifest in the registry instead.\n")
	out.WriteString("Details: `jig show <id>`, source: `jig src <id>`, run: `jig run <id>`.\n\n")
	out.WriteString("**Before writing a new script, find it here or with `jig ls <words>`.**\n\n")

	byKind := map[string][]Tool{}
	for _, tool := range tools {
		key := tool.Kind
		if tool.Status == "deprecated" {
			key = "deprecated"
		}
		byKind[key] = append(byKind[key], tool)
	}

	sections := []struct {
		kind, title, note string
	}{
		{"tool", "Tools", ""},
		{"env", "Secret profiles", "Not run on their own — they provide the environment for tools that reference them in `env`."},
		{"suite", "Suites", ""},
		{"deprecated", "Deprecated", "Do not use, kept for history."},
	}

	for _, section := range sections {
		group := byKind[section.kind]
		if len(group) == 0 {
			continue
		}
		sort.Slice(group, func(i, j int) bool { return group[i].ID < group[j].ID })

		fmt.Fprintf(&out, "## %s\n\n", section.title)
		if section.note != "" {
			fmt.Fprintf(&out, "%s\n\n", section.note)
		}

		out.WriteString("| id | what it does | safety | targets | path |\n")
		out.WriteString("|---|---|---|---|---|\n")
		for _, tool := range group {
			targets := strings.Join(tool.Targets, ", ")
			if targets == "" {
				targets = "—"
			}
			fmt.Fprintf(&out, "| `%s` | %s | %s | %s | `%s` |\n",
				tool.ID, escapePipes(tool.Summary), tool.Safety, targets, tool.Path)
		}
		out.WriteString("\n")
	}

	fmt.Fprintf(&out, "---\n\n%d entries · updated %s\n", len(tools), time.Now().Format("2006-01-02 15:04"))
	return out.String()
}

func escapePipes(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

func indexStale(cfg Config, tools []Tool) bool {
	if cfg.Index == "" || cfg.Index == "-" {
		return false
	}
	stat, err := os.Stat(cfg.Index)
	if err != nil {
		return true
	}
	for _, tool := range tools {
		manifest, manifestErr := os.Stat(tool.ManifestPath)
		if manifestErr == nil && manifest.ModTime().After(stat.ModTime()) {
			return true
		}
	}
	return false
}
